[assembly: CLSCompliant(false)]

[assembly: XmlnsDefinition("http://smart/maui", "Smart.Maui")]
[assembly: XmlnsDefinition("http://smart/maui", "Smart.Maui.Animations")]
[assembly: XmlnsDefinition("http://smart/maui", "Smart.Maui.Data")]
[assembly: XmlnsDefinition("http://smart/maui", "Smart.Maui.Interactivity")]
[assembly: XmlnsDefinition("http://smart/maui", "Smart.Maui.Markup")]
[assembly: XmlnsDefinition("http://smart/maui", "Smart.Maui.Resolver")]
[assembly: XmlnsDefinition("http://smart/maui", "Smart.Maui.Validation")]
[assembly: Microsoft.Maui.Controls.XmlnsPrefix("http://smart/maui", "s")]
